import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout components
import { Header, SideBar, ChatSection } from "@/components/layout";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="flex ">
          <SideBar />
          <div className="flex-1 space-y-8 overflow-y-auto max-h-screen">
            <Header />
            <main className="px-8 pb-8">{children}</main>
            <ChatSection />
          </div>
        </div>
      </body>
    </html>
  );
}
